name: Build and Push Docker image

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: arpit75/count-app:latest
    - name: Trigger EC2 update
      run: curl -X POST -d '{"push": {"changes": "true"}}' http://3.110.133.104:9000/hooks/update-docker-image
